{% set name = "napari-boxmanager" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_boxmanager-{{ version }}.tar.gz
  sha256: 0752a7ec684cee4ebce0739de5db2f3295870374cd39d4d66889df823ba949da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools-scm
  run:
    - matplotlib-base
    - mrcfile
    - napari >=0.4.18
    - numpy <=1.23.5  # https://github.com/napari/napari/issues/5484, should be fixed in the next napari release
    - pandas
    - pystardb >=0.4.2
    - python >=3.10
    - qtpy
    - scipy
    - tifffile
    - tqdm

test:
  imports:
    - box_manager
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/MPI-Dortmund/napari-boxmanager
  summary: Particle selection tool for cryo-em
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - mstabrin
