{% set name = "napari-boxmanager" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_boxmanager-{{ version }}.tar.gz
  sha256: 8d9420ff53895b2a803f9b39a81b1e470e4d11d90d03ec9b68776d533baf6b15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools-scm
  run:
    - matplotlib-base
    - mrcfile
    - napari
    - numpy <=1.23.5  # https://github.com/napari/napari/issues/5484, should be fixed in the next napari release
    - pandas
    - pystardb >=0.4.2
    - python >=3.10

test:
  imports:
    - box_manager
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MPI-Dortmund/napari-boxmanager
  summary: Particle selection tool for cryo-em
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - mstabrin
